classdef MW
    
    properties (Constant)
        constants = containers.Map({'HCl' 'O2' 'H2O_v' 'CO2' 'Cl2' 'CH4' 'CO' 'H2'}, ...
            { 36.458 ,...
              31.999 ,...
              18.01528,...
              44.01,...
              70.90,...
              16.04,...
              28.01,...
              2.016});      

    end
    
    methods
        function output_mw = get(self, name)
            %outputs the Cp of the given gas at the specified temperature 
            output_mw = self.constants(name);
        end
    end
end

